### ISSUE TITLE
Issues integrate this library with GLSP client , sprotty

### ISSUE THREAD

**Issue by MattiaRigon** [Aksem/sprotty-routing-libavoid#1]
Hi I'm trying to use this library to route my diagrams in my glsp and sprotty project. I'm following the instructions that you have written in your thesis. The error that I have is the following :
`Uncaught TypeError TypeError: Class constructor AbstractEdgeRouter cannot be invoked without 'new'.
Can you explain better how to integrate your project in other project ? 
Thanks a lot.

**Comment by Aksem** [comment]
Hi @MattiaRigon !
I'll update the usage manual either today or over the weekend with release of a new version and notify you.

**Comment by MattiaRigon** [comment]
Thanks a lot @Aksem

**Comment by MattiaRigon** [comment]
Hi @Aksem ,
have you any update about the usage manual?

**Comment by Aksem** [comment]
Hi @MattiaRigon ! Sorry, it took a bit longer than expected, but I just published release v1.1.1 with improved build configuration and comprehensive usage guide in README. Please test it, and if you still have problems, just let me know.
To test the new version in a real-world application, I integrated sprotty-routing-libavoid in [bigUML](https://github.com/borkdominik/bigUML) project(PR will come in the next days) and it works. So only issues related to specific environments can appear, but let's see.
